In [2]:
import pandas as pd

In [3]:
artists = pd.read_csv('author.csv')

In [4]:
artists

,author_id,author_name,year_of_birth,year_of_death,place_of_residence,author_description
0,0,Динара Хёртнагль,1988.0,NaN,Австрия,Динара Хёртнагль родилась в 1988 году в Екатер...
1,1,Кузнецова Анастасия,1986.0,NaN,Россия,Анастасия Кузнецова родилась в 1986 году в г. ...
2,2,Павел Рогатов,1995.0,NaN,Россия,Художник Павел Рогатов родился в 1995г в Подм...
3,3,Алексей Ланцев,1970.0,NaN,Россия,Родился в 1970 в городе Краснодаре. В 1986 око...
4,4,Миша Мост,1981.0,NaN,Россия,Художник и граффити райтер. Начал рисовать в 1...
...,...,...,...,...,...,...
169,169,Илья Slak,1986.0,NaN,Россия,Блинов Илья ака Slak - мультидисциплинарный ху...
170,170,Тимур Квадрат,1983.0,NaN,Россия,Тимур - разносторонний художник и фотограф. Ри...
171,171,Оскар Рабин,1928.0,2018.0,"СССР, Франция",Работы Оскара Рабина (1928-2018) относят к нон...
172,172,Валентина Кропивницкая,1924.0,2008.0,"СССР, Франция",Валентина Кропивницкая (1924 - 2008) - выдающа...
173,173,Владимир Немухин,1925.0,2016.0,Россия,Владимир Немухин (1925-2016) - яркий представи...

In [63]:
artist_works = pd.read_csv('product.csv')

In [65]:
artist_works['dimension_cm'] = artist_works[['length', 'width', 'height']].apply(
    lambda x: ' x '.join(x.dropna().astype(str)),
    axis=1
)
artist_works['dimension_cm'] = artist_works['dimension_cm'] +' см'

In [67]:
artist_works = artist_works[~artist_works['size_currency'].isin(['2012', '2018'])]

In [68]:
artist_works.loc[(artist_works['price_1_currency'] == 'euro'), 'price_1_currency'] = '€'
artist_works.loc[(artist_works['price_2_currency'] == 'dollar'), 'price_2_currency'] = '$'
artist_works.loc[(artist_works['price_3_currency'] == 'ruble'), 'price_3_currency'] = '₽'

C:\Users\Kseniya\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [70]:
artist_works.genre.value_counts()

zhivopis        518
printi          281
graphika        279
object          177
peyzazh          76
photographii     37
portret          37
collazh          14
video             3
abstraktsiya      2
Name: genre, dtype: int64

In [71]:
artist_works.loc[(artist_works['genre'] == 'zhivopis'), 'genre'] = 'Живопись'
artist_works.loc[(artist_works['genre'] == 'printi'), 'genre'] = 'Принт'
artist_works.loc[(artist_works['genre'] == 'graphika'), 'genre'] = 'Графика'
artist_works.loc[(artist_works['genre'] == 'object'), 'genre'] = 'Объект'
artist_works.loc[(artist_works['genre'] == 'peyzazh'), 'genre'] = 'Пейзаж'
artist_works.loc[(artist_works['genre'] == 'photographii'), 'genre'] = 'Фотография'
artist_works.loc[(artist_works['genre'] == 'portret'), 'genre'] = 'Портрет'
artist_works.loc[(artist_works['genre'] == 'collazh'), 'genre'] = 'Коллаж'
artist_works.loc[(artist_works['genre'] == 'video'), 'genre'] = 'Видео'
artist_works.loc[(artist_works['genre'] == 'abstraktsiya'), 'genre'] = 'Абстракция'

C:\Users\Kseniya\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [75]:
artist_works

,product_id,author_id,product_name,execution_technique,length,width,height,size_currency,year,year_1,price_1,price_1_currency,price_2,price_2_currency,price_3,price_3_currency,genre,dimension_cm
0,0,0,Серия Skylights,"Холст, акрил",40,30,NaN,см,2021,NaN,315,€,366,$,26059,₽,Живопись,40 x 30 см
1,1,0,Серия Skylights,"Холст на круглом подрамнике, акрил",50,50,NaN,см,2021,NaN,455,€,528,$,37641,₽,Живопись,50 x 50 см
2,2,0,Серия Skylights,"Холст на круглом подрамнике, акрил",50,50,NaN,см,2021,NaN,350,€,406,$,28955,₽,Живопись,50 x 50 см
3,3,0,Серия Skylights,"Холст на круглом подрамнике, акрил",50,50,NaN,см,2021,NaN,503,€,584,$,41612,₽,Живопись,50 x 50 см
4,4,0,Серия Skylights,"Холст на круглом подрамнике, акрил",30,30,NaN,см,2021,NaN,235,€,273,$,19441,₽,Живопись,30 x 30 см
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,1426,41,Пальмовый лес,"бумага, пастель",21,15,NaN,см,2016,NaN,700,€,811,$,57721,₽,Пейзаж,21 x 15 см
1422,1427,29,"Семь ранних версий циклона Сатоши, v-6","графит, полировка, акрил на дереве",50,50,NaN,см,2018,NaN,2800,€,3244,$,230886,₽,Пейзаж,50 x 50 см
1423,1428,29,Чарли,"дерево, графит",50,50,NaN,см,2016,NaN,1700,€,1970,$,140181,₽,Пейзаж,50 x 50 см
1424,1429,29,Пейзаж. Хакасия 3,"картон, акрил",69,49,NaN,см,2010,NaN,300,€,348,$,24738,₽,Пейзаж,69 x 49 см
1425,1430,29,Рельеф №2,"гипс, масляная краска",14.3,20,NaN,см,2015,NaN,1200,€,1390,$,98951,₽,Пейзаж,14.3 x 20 см